//! Game events

use flint_core::EntityId;

/// Events generated by the runtime (collisions, input actions, custom)
#[derive(Debug, Clone)]
pub enum GameEvent {
    /// Two entities started colliding
    CollisionStarted {
        entity_a: EntityId,
        entity_b: EntityId,
    },
    /// Two entities stopped colliding
    CollisionEnded {
        entity_a: EntityId,
        entity_b: EntityId,
    },
    /// An entity entered a trigger volume
    TriggerEntered {
        entity: EntityId,
        trigger: EntityId,
    },
    /// An entity exited a trigger volume
    TriggerExited {
        entity: EntityId,
        trigger: EntityId,
    },
    /// An input action was pressed
    ActionPressed(String),
    /// An input action was released
    ActionReleased(String),
    /// Custom event for scripting/gameplay
    Custom {
        name: String,
        data: toml::Value,
    },
}
