// crates/flint-render/src/ocean_pipeline.rs
//! Gerstner ocean rendering pipeline.
//!
//! One static grid mesh — normalized [-1,1]² coordinates, radially warped in
//! the vertex shader so the center is dense and the rim reaches kilometers —
//! follows the camera via a snapped `grid_offset` uniform. Vertices displace
//! with the wave array generated by `flint_core::ocean::WaveSpectrum` (the
//! CPU/GPU parity keystone: the GPU only sums what the CPU generated).
//!
//! Bind groups: 0 = transforms (shared), 1 = OceanUniforms, 2 = lights +
//! shadows (shared). Group 3 stays free for the M4 refraction grab-pass.

use bytemuck::{Pod, Zeroable};
use flint_core::ocean::MAX_WAVES;
use flint_core::toml_util::{toml_color, toml_f32};
use wgpu::util::DeviceExt;

/// Grid resolution (cells per side). 256 → 66k vertices, ~0.5 MB.
pub const OCEAN_GRID_CELLS: u32 = 256;

/// Uniform block — layout must match `OceanUniforms` in ocean_shader.wgsl.
#[repr(C)]
#[derive(Copy, Clone, Debug, Pod, Zeroable)]
pub struct OceanUniformsGpu {
    /// Two vec4 per wave: [dir.x, dir.y, k, amp], [phase_t, q, 0, 0].
    pub waves: [[f32; 4]; MAX_WAVES * 2],
    pub deep_color: [f32; 4],
    pub shallow_color: [f32; 4],
    pub foam_color: [f32; 4],
    pub sss_color: [f32; 4],
    pub grid_offset: [f32; 2],
    pub num_waves: u32,
    pub enable_tonemapping: u32,
    pub grid_scale: f32,
    pub fade_start: f32,
    pub fade_end: f32,
    pub foam_threshold: f32,
    pub foam_noise_scale: f32,
    pub ramp_steps: f32,
    pub specular_strength: f32,
    pub time: f32,
    // ── Refraction / turbidity (grab pass) ──
    pub absorption_color: [f32; 3],
    pub turbidity: f32,
    pub refraction_strength: f32,
    pub camera_near: f32,
    pub camera_far: f32,
    /// 1 when the grab pass ran this frame (scene color/depth are valid).
    pub grab_enabled: u32,
    /// Scene fog color (rgb) + self-fog strength (a) for the horizon fade.
    pub fog_color: [f32; 4],
    /// Sky gradient snapshot for analytic reflections (from the `sky`
    /// component; strength 0 when the scene has no procedural sky).
    pub sky_zenith: [f32; 4],
    pub sky_horizon: [f32; 4],
    pub sky_haze: [f32; 4],
    pub sky_reflection_strength: f32,
    // ── Contact foam (splash ring around the `ocean_contact` hull) ──
    /// Overall gain; forced 0 when the scene has no contact entity.
    pub splash_strength: f32,
    /// Max foam band width outward from the hull at full churn (m).
    pub splash_width: f32,
    /// Lapping-animation rate.
    pub splash_flicker_speed: f32,
    /// [center.x, center.z, cos(yaw), sin(yaw)] of the contact hull.
    pub raft_a: [f32; 4],
    /// [half_x, half_z, splash_baseline, splash_noise_scale].
    pub raft_b: [f32; 4],
    /// [hull_vel.x, hull_vel.y, hull_vel.z, splash_response].
    pub raft_c: [f32; 4],
    // ── Cel band edge treatment ──
    /// Noise wobble amplitude on the diffuse ramp, in shade units (0 = off).
    pub band_wobble: f32,
    /// Halftone transition width at band edges (0 = hard line, 1 = full band).
    pub band_dither: f32,
    /// World-space halftone dot grid frequency (dots per meter).
    pub band_dither_scale: f32,
    /// Rain impact-ring density 0..1 (weather-driven; 0 = off).
    pub rain_ripple: f32,
    // ── Bioluminescent foam ──
    /// Emissive glow rgb + strength in .a (TOD script fades it in at night).
    pub foam_glow: [f32; 4],
    // ── Reality-tear render mode (mirrors PostProcessConfig) ──
    /// 2 = blood ocean; other modes leave the water alone.
    pub mode: u32,
    /// Blend strength 0..1 for the active mode.
    pub mode_mix: f32,
    pub _pad_mode: [f32; 2],
}

/// Visual (non-simulation) parameters of the `ocean` component.
/// Simulation params live in `flint_core::ocean::OceanParams`.
#[derive(Debug, Clone, PartialEq)]
pub struct OceanVisuals {
    pub deep_color: [f32; 4],
    pub shallow_color: [f32; 4],
    pub foam_color: [f32; 4],
    pub sss_color: [f32; 4],
    pub grid_scale: f32,
    pub fade_start: f32,
    pub fade_end: f32,
    pub foam_threshold: f32,
    pub foam_noise_scale: f32,
    pub ramp_steps: f32,
    pub specular_strength: f32,
    /// Water cloudiness: 0 = glass-clear, higher = murk sooner (1/m-ish).
    pub turbidity: f32,
    /// Screen-space refraction distortion strength.
    pub refraction_strength: f32,
    /// Per-channel absorption tint (red absorbs first in seawater).
    pub absorption_color: [f32; 3],
    /// Fresnel-weighted analytic sky reflection amount (0 disables).
    pub sky_reflection_strength: f32,
    /// Contact foam overall gain (0 disables).
    pub splash_strength: f32,
    /// Max contact foam band width at full churn (m).
    pub splash_width: f32,
    /// Contact foam lapping/flicker animation rate.
    pub splash_flicker_speed: f32,
    /// World-space frequency of the contact foam scalloped edge.
    pub splash_noise_scale: f32,
    /// Churn floor on calm water (0 = foam vanishes when flat).
    pub splash_baseline: f32,
    /// Impact speed → churn gain (s/m).
    pub splash_response: f32,
    /// Cel ramp edge wobble amplitude (0 = razor band contours).
    pub band_wobble: f32,
    /// Halftone dither width at band edges (0 = hard line).
    pub band_dither: f32,
    /// Halftone dot grid frequency (dots per meter).
    pub band_dither_scale: f32,
    /// Rain impact-ring density (0 = none; weather.rhai drives it with rain).
    pub rain_ripple: f32,
    /// Bioluminescent foam glow color (emissive; not TOD-lit by design —
    /// it IS a light source. The strength below is what TOD animates).
    pub foam_glow_color: [f32; 4],
    /// Bioluminescent glow strength (0 = off; time_of_day.rhai drives it).
    pub foam_glow: f32,
}

impl Default for OceanVisuals {
    fn default() -> Self {
        Self {
            // Bold flat blues per the stylized references.
            deep_color: [0.055, 0.22, 0.53, 1.0],
            shallow_color: [0.16, 0.51, 0.83, 1.0],
            foam_color: [0.96, 0.99, 1.0, 1.0],
            sss_color: [0.10, 0.75, 0.75, 1.0],
            grid_scale: 60.0,
            fade_start: 90.0,
            fade_end: 170.0,
            foam_threshold: 0.62,
            foam_noise_scale: 0.35,
            ramp_steps: 3.0,
            specular_strength: 1.0,
            turbidity: 0.8,
            refraction_strength: 0.6,
            absorption_color: [0.9, 0.35, 0.22],
            sky_reflection_strength: 0.8,
            splash_strength: 1.0,
            splash_width: 0.35,
            splash_flicker_speed: 1.6,
            splash_noise_scale: 1.8,
            splash_baseline: 0.15,
            splash_response: 1.0,
            band_wobble: 0.20,
            band_dither: 0.0,
            band_dither_scale: 1.5,
            rain_ripple: 0.0,
            // Teal-green sea sparkle (dinoflagellate blue-green).
            foam_glow_color: [0.35, 0.95, 0.75, 1.0],
            foam_glow: 0.0,
        }
    }
}

impl OceanVisuals {
    pub fn from_component(value: &toml::Value) -> Self {
        let d = Self::default();
        let f = |name: &str, dv: f32| value.get(name).and_then(toml_f32).unwrap_or(dv);
        let c = |name: &str, dv: [f32; 4]| value.get(name).and_then(toml_color).unwrap_or(dv);
        Self {
            deep_color: c("deep_color", d.deep_color),
            shallow_color: c("shallow_color", d.shallow_color),
            foam_color: c("foam_color", d.foam_color),
            sss_color: c("sss_color", d.sss_color),
            grid_scale: f("grid_scale", d.grid_scale).clamp(10.0, 500.0),
            fade_start: f("fade_start", d.fade_start).max(5.0),
            fade_end: f("fade_end", d.fade_end).max(10.0),
            foam_threshold: f("foam_threshold", d.foam_threshold),
            foam_noise_scale: f("foam_noise_scale", d.foam_noise_scale).max(0.001),
            ramp_steps: f("ramp_steps", d.ramp_steps).clamp(1.0, 8.0),
            specular_strength: f("specular_strength", d.specular_strength).max(0.0),
            turbidity: f("turbidity", d.turbidity).max(0.0),
            refraction_strength: f("refraction_strength", d.refraction_strength).max(0.0),
            absorption_color: value
                .get("absorption_color")
                .and_then(flint_core::toml_util::toml_vec3)
                .unwrap_or(d.absorption_color),
            sky_reflection_strength: f("sky_reflection_strength", d.sky_reflection_strength)
                .clamp(0.0, 2.0),
            splash_strength: f("splash_strength", d.splash_strength).clamp(0.0, 4.0),
            splash_width: f("splash_width", d.splash_width).max(0.01),
            splash_flicker_speed: f("splash_flicker_speed", d.splash_flicker_speed).max(0.0),
            splash_noise_scale: f("splash_noise_scale", d.splash_noise_scale).max(0.01),
            splash_baseline: f("splash_baseline", d.splash_baseline).clamp(0.0, 1.0),
            splash_response: f("splash_response", d.splash_response).clamp(0.0, 8.0),
            band_wobble: f("band_wobble", d.band_wobble).clamp(0.0, 1.0),
            band_dither: f("band_dither", d.band_dither).clamp(0.0, 1.0),
            band_dither_scale: f("band_dither_scale", d.band_dither_scale).clamp(0.05, 32.0),
            rain_ripple: f("rain_ripple", d.rain_ripple).clamp(0.0, 1.0),
            foam_glow_color: c("foam_glow_color", d.foam_glow_color),
            foam_glow: f("foam_glow", d.foam_glow).clamp(0.0, 2.0),
        }
    }

    /// The world-space snap quantum for grid_offset: one inner grid cell.
    /// Snapping the offset to cell multiples keeps wave sampling positions
    /// world-anchored (no "swimming" as the camera moves).
    pub fn snap_quantum(&self) -> f32 {
        // Inner cell size ≈ grid_scale * (2 / cells) / 1.02 at the center.
        self.grid_scale * 2.0 / OCEAN_GRID_CELLS as f32
    }
}

/// Ocean grid vertex: just normalized 2D coordinates; everything else is
/// derived in the shader.
#[repr(C)]
#[derive(Copy, Clone, Debug, Pod, Zeroable)]
pub struct OceanVertex {
    pub pos: [f32; 2],
}

impl OceanVertex {
    const ATTRIBS: [wgpu::VertexAttribute; 1] = wgpu::vertex_attr_array![0 => Float32x2];

    pub fn desc() -> wgpu::VertexBufferLayout<'static> {
        wgpu::VertexBufferLayout {
            array_stride: std::mem::size_of::<OceanVertex>() as wgpu::BufferAddress,
            step_mode: wgpu::VertexStepMode::Vertex,
            attributes: &Self::ATTRIBS,
        }
    }
}

/// Generate the normalized grid: (cells+1)² vertices spanning [-1, 1]².
pub fn generate_ocean_grid(cells: u32) -> (Vec<OceanVertex>, Vec<u32>) {
    let n = cells + 1;
    let mut vertices = Vec::with_capacity((n * n) as usize);
    for j in 0..n {
        for i in 0..n {
            let x = i as f32 / cells as f32 * 2.0 - 1.0;
            let z = j as f32 / cells as f32 * 2.0 - 1.0;
            vertices.push(OceanVertex { pos: [x, z] });
        }
    }
    let mut indices = Vec::with_capacity((cells * cells * 6) as usize);
    for j in 0..cells {
        for i in 0..cells {
            let a = j * n + i;
            let b = a + 1;
            let c = a + n;
            let d = c + 1;
            indices.extend_from_slice(&[a, c, b, b, c, d]);
        }
    }
    (vertices, indices)
}

/// The ocean render pipeline plus its static grid mesh and the grab-pass
/// blit pipeline (snapshots opaque scene color/depth for refraction).
pub struct OceanPipeline {
    pub pipeline: wgpu::RenderPipeline,
    pub ocean_bind_group_layout: wgpu::BindGroupLayout,
    /// Group 3: grabbed scene color (Rgba16Float) + depth-as-R32Float.
    pub grab_bind_group_layout: wgpu::BindGroupLayout,
    pub blit_pipeline: wgpu::RenderPipeline,
    pub blit_bind_group_layout: wgpu::BindGroupLayout,
    pub grid_vertex_buffer: wgpu::Buffer,
    pub grid_index_buffer: wgpu::Buffer,
    pub grid_index_count: u32,
}

/// Create a 1x1 texture usable as a grab-pass placeholder binding.
pub fn create_dummy_grab_texture(
    device: &wgpu::Device,
    format: wgpu::TextureFormat,
    label: &str,
) -> wgpu::Texture {
    device.create_texture(&wgpu::TextureDescriptor {
        label: Some(label),
        size: wgpu::Extent3d {
            width: 1,
            height: 1,
            depth_or_array_layers: 1,
        },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format,
        usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::RENDER_ATTACHMENT,
        view_formats: &[],
    })
}

impl OceanPipeline {
    pub fn new(
        device: &wgpu::Device,
        scene_format: wgpu::TextureFormat,
        transform_layout: &wgpu::BindGroupLayout,
        light_layout: &wgpu::BindGroupLayout,
    ) -> Self {
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("Ocean Shader"),
            source: wgpu::ShaderSource::Wgsl(include_str!("ocean_shader.wgsl").into()),
        });

        let ocean_bind_group_layout =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                entries: &[wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::VERTEX | wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                }],
                label: Some("Ocean Bind Group Layout"),
            });

        // Group 3: grabbed scene color + depth (textureLoad — no samplers).
        let non_filtering_tex = |binding: u32| wgpu::BindGroupLayoutEntry {
            binding,
            visibility: wgpu::ShaderStages::FRAGMENT,
            ty: wgpu::BindingType::Texture {
                sample_type: wgpu::TextureSampleType::Float { filterable: false },
                view_dimension: wgpu::TextureViewDimension::D2,
                multisampled: false,
            },
            count: None,
        };
        let grab_bind_group_layout =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                entries: &[non_filtering_tex(0), non_filtering_tex(1)],
                label: Some("Ocean Grab Bind Group Layout"),
            });

        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            bind_group_layouts: &[
                transform_layout,         // group 0
                &ocean_bind_group_layout, // group 1
                light_layout,             // group 2
                &grab_bind_group_layout,  // group 3
            ],
            push_constant_ranges: &[],
            label: Some("Ocean Pipeline Layout"),
        });

        let pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("Ocean Pipeline"),
            layout: Some(&pipeline_layout),
            vertex: wgpu::VertexState {
                module: &shader,
                entry_point: Some("vs_main"),
                buffers: &[OceanVertex::desc()],
                compilation_options: Default::default(),
            },
            fragment: Some(wgpu::FragmentState {
                module: &shader,
                entry_point: Some("fs_main"),
                targets: &[Some(wgpu::ColorTargetState {
                    format: scene_format,
                    blend: None, // opaque; depth-written so composite fog applies
                    write_mask: wgpu::ColorWrites::ALL,
                })],
                compilation_options: Default::default(),
            }),
            primitive: wgpu::PrimitiveState {
                topology: wgpu::PrimitiveTopology::TriangleList,
                // Steep displaced triangles can face away briefly; draw both sides.
                cull_mode: None,
                ..Default::default()
            },
            depth_stencil: Some(wgpu::DepthStencilState {
                format: wgpu::TextureFormat::Depth32Float,
                depth_write_enabled: true,
                depth_compare: wgpu::CompareFunction::Less,
                stencil: Default::default(),
                bias: Default::default(),
            }),
            multisample: Default::default(),
            multiview: None,
            cache: None,
        });

        // ── Grab blit pipeline: opaque scene color+depth → sampleable copies ──
        let blit_shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("Grab Blit Shader"),
            source: wgpu::ShaderSource::Wgsl(include_str!("grab_blit_shader.wgsl").into()),
        });
        let blit_bind_group_layout =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                entries: &[
                    non_filtering_tex(0),
                    wgpu::BindGroupLayoutEntry {
                        binding: 1,
                        visibility: wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Texture {
                            sample_type: wgpu::TextureSampleType::Depth,
                            view_dimension: wgpu::TextureViewDimension::D2,
                            multisampled: false,
                        },
                        count: None,
                    },
                ],
                label: Some("Grab Blit Bind Group Layout"),
            });
        let blit_pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            bind_group_layouts: &[&blit_bind_group_layout],
            push_constant_ranges: &[],
            label: Some("Grab Blit Pipeline Layout"),
        });
        let blit_pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("Grab Blit Pipeline"),
            layout: Some(&blit_pipeline_layout),
            vertex: wgpu::VertexState {
                module: &blit_shader,
                entry_point: Some("vs_blit"),
                buffers: &[],
                compilation_options: Default::default(),
            },
            fragment: Some(wgpu::FragmentState {
                module: &blit_shader,
                entry_point: Some("fs_blit"),
                targets: &[
                    Some(wgpu::ColorTargetState {
                        format: crate::postprocess::HDR_FORMAT,
                        blend: None,
                        write_mask: wgpu::ColorWrites::ALL,
                    }),
                    Some(wgpu::ColorTargetState {
                        format: wgpu::TextureFormat::R32Float,
                        blend: None,
                        write_mask: wgpu::ColorWrites::ALL,
                    }),
                ],
                compilation_options: Default::default(),
            }),
            primitive: wgpu::PrimitiveState {
                topology: wgpu::PrimitiveTopology::TriangleList,
                cull_mode: None,
                ..Default::default()
            },
            depth_stencil: None,
            multisample: Default::default(),
            multiview: None,
            cache: None,
        });

        let (vertices, indices) = generate_ocean_grid(OCEAN_GRID_CELLS);
        let grid_vertex_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("Ocean Grid Vertex Buffer"),
            contents: bytemuck::cast_slice(&vertices),
            usage: wgpu::BufferUsages::VERTEX,
        });
        let grid_index_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("Ocean Grid Index Buffer"),
            contents: bytemuck::cast_slice(&indices),
            usage: wgpu::BufferUsages::INDEX,
        });

        Self {
            pipeline,
            ocean_bind_group_layout,
            grab_bind_group_layout,
            blit_pipeline,
            blit_bind_group_layout,
            grid_vertex_buffer,
            grid_index_buffer,
            grid_index_count: indices.len() as u32,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn uniform_struct_matches_wgsl_layout() {
        // waves(512) + 4 colors(64) + grid_offset(8) + 2×u32(8) + 8×f32(32)
        // + absorption vec3+turbidity(16) + refr/near/far/grab(16)
        // + fog_color(16) + sky snapshot 3×vec4 + strength(64, incl. 3
        // splash scalars) + contact hull 3×vec4(48) + band edge 4×f32(16)
        // + foam_glow vec4(16) + mode u32 + mode_mix + pad2 (16) = 832
        assert_eq!(std::mem::size_of::<OceanUniformsGpu>(), 832);
        assert_eq!(832 % 16, 0, "uniform size must be 16-byte aligned");
    }

    #[test]
    fn grid_indices_reference_valid_vertices() {
        let (verts, indices) = generate_ocean_grid(8);
        assert_eq!(verts.len(), 81);
        assert_eq!(indices.len(), 8 * 8 * 6);
        assert!(indices.iter().all(|&i| (i as usize) < verts.len()));
    }
}
